on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Merge Main into Dev

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B main -H dev --title 'Merge main into dev' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
